/* Committed prototype review operations.
 *
 * Do not edit this file by hand. Reviewers add comments in the prototype,
 * choose "Export for repository", replace this file, and commit it. Operations
 * are append-only and identified by id; delete operations are tombstones, so
 * merging reviewer exports cannot silently resurrect deleted feedback.
 *
 * `prototypeId` must stay equal to PROTOTYPE_ID in generate.mjs.
 */
window.__OM_PROTOTYPE_COMMENTS__ = {
  version: 2,
  prototypeId: 'factory-intake',
  operations: []
};
